### ISSUE TITLE
请教横滚角自动平衡问题

### ISSUE THREAD

**Issue by flamebox** [HuGuoXuang/Hyun#3]
请问这版开源代码有实现视频上的横滚角自动平衡吗？我读代码关于这部分不是很理解，不知道具体是哪步实现的。

另外，请问jdbz这个变量具体是什么作用呢，处于这个模式下，似乎是根据ab两边的高度实时调整了速度环和平衡环的pid参数
`Abalance.Kp = -0.00002*sq(ah)+0.0357*ah+1.9519;     
  Abalance.Ki = 0.0005*sq(ah)+0.1415*ah+11.045;     
  Abalance.Kd = 0; 

  Avelocity.Kp = 0.00001*sq(ah)-0.0025*ah+0.2509;    
  Avelocity.Ki = 0.00003*sq(ah)-0.0053*ah+0.303;     
  Avelocity.Kd = 0;     

  Bbalance.Kp = -0.00002*sq(bh)+0.0357*bh+1.9519;     
  Bbalance.Ki = 0.0005*sq(bh)+0.1415*bh+11.045;     
  Bbalance.Kd = 0; 

  Bvelocity.Kp = 0.00001*sq(bh)-0.0025*bh+0.2509;    
  Bvelocity.Ki = 0.00003*sq(bh)-0.0053*bh+0.303;     
  Bvelocity.Kd = 0;  `
这里的各种系数到底怎么确定的？根据什么理论模型的呢？

最后实时高度的计算AH = 140+ah1+ah2-53.9，这个140和53.9到底是怎么的出来的啊？

我对你这个机器人十分感兴趣，有强烈的愿望想自己学习复现，但本人才疏学浅，不理解的问题比较多，望赐教，谢谢

**Comment by HuGuoXuang** [comment]
jdbz 判断轮腿是否摔倒  用来切换摔倒时的PID参数  这份代码就是视频看到效果的源代码  代码都是想到什么就写什么  写得比较乱 没有用到数学模型 理论除了PID就没了   如果你要用搞数学建模 你可以简单的看成两个可以改变摆杆长度的倒立摆 不过要做一些限制 比如倾斜角度是一样

**Comment by flamebox** [comment]
> 

感谢作者回复。最近也在不断学习，收获颇大。
