### ISSUE TITLE
请问舵机的型号是？或者说选择舵机有什么参考吗？

### ISSUE THREAD

**Issue by South-River** [HuGuoXuang/Hyun#6]
如题

**Comment by HuGuoXuang** [comment]
资料里的图片有舵机和电机的型号    选择舵机主要考虑机器重量和腿部的加速度是否大于重力加速度g

**Comment by flamebox** [comment]
> 资料里的图片有舵机和电机的型号 选择舵机主要考虑机器重量和腿部的加速度是否大于重力加速度g

车子复现出来了，现在发现舵机控制升起时，有点不够力，也不顺畅，是否电流不够？一定要用图片里的航模电池规格吗？一般12v的18650电池组行不行？

**Comment by HuGuoXuang** [comment]
检查稳压模块是否有调节到8.4V  稳压模块是给舵机供电的 建议用航模电池 机器的工作电流比较大

**Comment by HuGuoXuang** [comment]
> > 资料里的图片有舵机和电机的型号 选择舵机主要考虑机器重量和腿部的加速度是否大于重力加速度g
> 
> 车子复现出来了，现在发现舵机控制升起时，有点不够力，也不顺畅，是否电流不够？一定要用图片里的航模电池规格吗？一般12v的18650电池组行不行？

检查文稳压模块的电压是否调节到8.4V  高压舵机供电在8.4V  建议用航模电池 机器的工作电流比较大
